package com.springboot.library1.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.sun.istack.NotNull;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "tb_author")
@AllArgsConstructor
@Getter
@Setter
@ToString(exclude = "books")
@EqualsAndHashCode
@ApiModel(value = "Author",description = "Entity to represent an Author in a Library System")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) @ApiModelProperty("Autogenerated Primary key of type Long")
    private Long id;

    @Column(nullable = false)
    private String name;
    @Column(nullable = false)
    private String lastName;
    @Column(nullable = false, unique = true) @ApiModelProperty("Unique attribute")
    private String email;

    @JsonIgnore
    @OneToMany(mappedBy = "author" /*, cascade = CascadeType.ALL*/)
    @Setter(AccessLevel.NONE)
    private List<Book> books= new ArrayList<>();

    public Author(){
    }

}
