package com.springboot.library1.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.persistence.*;

@Entity
@Table(name = "tb_book")
@AllArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode
@ApiModel(value = "Book",description = "Entity to represent a Book in a Library System")
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) @ApiModelProperty("Autogenerated Primary key of type Long")
    private Long id;

    @Column(unique = true,nullable = false) @ApiModelProperty("Unique attribute")
    private String isbn;

    @Column(nullable = false)
    private String name;
    @Column(nullable = false)
    private String edition;
    @Column(nullable = false)
    private Integer publicationYear;

    @ManyToOne
    @JoinColumn(name = "id_author")
    private Author author;

    public Book(){
    }

    /*
    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", edition='" + edition + '\'' +
                '}';
    }*/

}